import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {existsSync, readFileSync, writeFileSync, mkdirSync, renameSync} from 'node:fs';
import {resolve, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright';

const root=process.env.NIGHTSHIFT_BROWSER_PROJECT, url=process.env.NIGHTSHIFT_BROWSER_URL;
assert(root && url, 'Use npm run test:browser to prepare isolated fixtures');
const repo=resolve(dirname(fileURLToPath(import.meta.url)), '..');
const artifacts=resolve(process.env.NIGHTSHIFT_BROWSER_ARTIFACTS || resolve(repo,'test-output/browser'));
mkdirSync(artifacts,{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.url().endsWith('/api/operations')) console.log('operation',r.request().postDataJSON()?.action,r.status());});
const cli=(...args)=>JSON.parse(execFileSync('bash',[resolve(repo,'scripts/nightshift-factory.sh'),'ops',...args,'--project',root],{env:process.env,encoding:'utf8'}));
const calls=()=>readFileSync(resolve(root,'.synthetic-calls.jsonl'),'utf8').trim().split('\n').length;
const panel=page.getByRole('region',{name:'Engineering operations'});
async function assess(){
  const response=page.waitForResponse(r=>r.url().includes('/api/operations?task='));
  await panel.getByRole('button',{name:'Assess operations',exact:true}).click();
  const value=await (await response).json();
  await panel.getByRole('button',{name:'Assess operations',exact:true}).waitFor({state:'visible'});
  await page.waitForFunction(()=>!document.querySelector('[aria-label="Engineering operations"] input').disabled);
  return value.view;
}
async function execute(action='chain'){
  const response=page.waitForResponse(r=>r.url().endsWith('/api/operations') && r.request().postDataJSON()?.action===action,{timeout:90000});
  await panel.getByRole('button',{name:'Authorize and run selected operations',exact:true}).click();
  const value=await (await response).json();
  await page.waitForFunction(()=>!document.querySelector('[aria-label="Engineering operations"] input').disabled);
  return value;
}
function sameView(a,b){delete a.usage;delete b.usage;assert.deepEqual(a,b);}
try {
  const scenarios=JSON.parse(readFileSync(resolve(root,'scenarios.json'),'utf8'));scenarios.cases[0].manual=true;writeFileSync(resolve(root,'scenarios.json'),JSON.stringify(scenarios));
  const initial=cli('assess','demo','groom-spec');
  const question=cli('question','demo','groom-spec','--binding',initial.binding,'--question',JSON.stringify({question:'Which return behavior is intended?',reason:'Clarify the current synthetic request before implementation.',options:[{id:'two',label:'Return two',description:'Keep the declared behavior.'}]}));
  await page.goto(url);
  await panel.getByLabel('Task key').fill('demo');
  let view=await assess();sameView(view,cli('view','demo'));
  assert(await panel.getByRole('button',{name:'Select implement',exact:true}).isDisabled());
  await panel.getByLabel('Answer for groom-spec').fill('Return two as specified.');
  const answered=page.waitForResponse(r=>r.url().endsWith('/api/operations')&&r.request().postDataJSON()?.action==='answer');
  await panel.getByRole('button',{name:'Save answer without running',exact:true}).click();assert((await answered).ok());
  await page.waitForFunction(()=>!document.querySelector('[aria-label="Engineering operations"] input').disabled);
  assert(!existsSync(resolve(root,'.synthetic-calls.jsonl')));
  await page.reload();await panel.getByLabel('Task key').fill('demo');await assess();
  assert(await panel.getByText('Saved answer: Return two as specified.',{exact:true}).isVisible());
  await panel.getByLabel('Operator identity').fill('synthetic-browser-operator');
  await panel.getByRole('button',{name:'Select factory recipe',exact:true}).click();
  let result=await execute();assert.equal(result.view.status,'pending_manual_acceptance');assert.equal(calls(),4);
  const originalResults=structuredClone(result.results);
  sameView(await assess(),cli('view','demo'));
  await panel.screenshot({path:resolve(artifacts,'operations-pending-acceptance.png')});
  await panel.getByText('Retained authorizations and recovery',{exact:true}).click();
  const replay=page.waitForResponse(r=>r.url().endsWith('/api/operations') && r.request().postDataJSON()?.action==='chain');
  await panel.getByRole('button',{name:/^Resume /}).first().click();
  result=await (await replay).json();assert.deepEqual(result.results.map(({next_action,...receipt})=>receipt),originalResults.map(({next_action,...receipt})=>receipt));assert.equal(calls(),4);
  await page.waitForFunction(()=>!document.querySelector('[aria-label="Engineering operations"] input').disabled);
  await panel.getByText('Retained authorizations and recovery',{exact:true}).click();
  await panel.getByRole('button',{name:'Select factory recipe',exact:true}).click();
  await panel.getByLabel('Repair eligible failures within this allowance').check();
  result=await execute('supervise');assert.equal(result.status,'passed');assert.equal(calls(),4);
  sameView(await assess(),cli('view','demo'));
  await panel.getByRole('button',{name:'Select accept',exact:true}).click();
  assert(await panel.getByRole('button',{name:'Authorize and run selected operations',exact:true}).isDisabled());
  await panel.getByLabel('Observed result for two').fill('Observed return value two in the synthetic interface.');
  await panel.getByLabel('Evidence note for two').fill('Synthetic browser observation at this assessed revision.');
  await panel.getByLabel('Manual case two passed',{exact:true}).check();
  await panel.getByLabel('I accept this exact reviewed evidence and the recorded case observations.',{exact:true}).check();result=await execute();assert.equal(result.results[0].status,'passed');assert.equal(calls(),4);
  // Source drift must remove approval; explicit external adoption cannot repeat Implement.
  writeFileSync(resolve(root,'app.py'),'def answer():\n    return 3\n');
  view=await assess();assert.notEqual(view.operations.find(r=>r.operation==='accept').status,'current');
  await panel.getByRole('button',{name:'Select adopt',exact:true}).click();
  await panel.getByLabel('External author identity').fill('synthetic-external-author');
  await panel.getByLabel('Actual author provider').selectOption('human');
  result=await execute();assert.equal(result.results[0].status,'passed');assert.equal(calls(),4);
  await panel.getByRole('button',{name:'Select verify',exact:true}).click();
  result=await execute();assert.equal(result.results[0].status,'failed');assert.equal(calls(),4);
  assert((await panel.getByRole('alert').innerText()).length>0);
  assert(await panel.getByRole('button',{name:'Select review',exact:true}).isDisabled());
  sameView(await assess(),cli('view','demo'));
  await panel.getByRole('button',{name:'Select verify',exact:true}).scrollIntoViewIfNeeded();
  await panel.screenshot({path:resolve(artifacts,'operations-failed-verification.png')});
  await page.reload();await panel.getByLabel('Task key').fill('demo');view=await assess();
  assert.equal(view.operations.find(r=>r.operation==='verify').status,'blocked');
  assert(view.attempts.some(r=>r.operation==='verify' && r.status==='failed'));
  assert(view.operations.find(r=>r.operation==='verify').findings.length>0);
  // Exhaust a separate ticket through bounded repair, then adopt external work.
  mkdirSync(resolve(root,'docs/exhausted'),{recursive:true});
  writeFileSync(resolve(root,'docs/exhausted/operations.json'),readFileSync(resolve(root,'docs/demo/operations.json')));
  writeFileSync(resolve(root,'app.py'),'def answer():\n    return 2\n');
  writeFileSync(resolve(root,'test_app.py'),'import unittest\nfrom app import answer\nclass Test(unittest.TestCase):\n    def test_answer(self): self.assertEqual(answer(),2)\nunittest.main()\n');
  writeFileSync(resolve(root,'.synthetic-review-failure'),'synthetic bounded review rejection');
  await panel.getByLabel('Task key').fill('exhausted');await assess();
  await panel.getByLabel('Operator identity').fill('synthetic-browser-operator');
  await panel.getByRole('button',{name:'Select factory recipe',exact:true}).click();
  await panel.getByLabel('Repair eligible failures within this allowance').check();
  const beforeExhaustion=calls();result=await execute('supervise');
  assert.equal(result.status,'blocked');assert.equal(result.supervisor.reason,'repair_limit_exhausted');assert.equal(calls()-beforeExhaustion,8);
  assert(await panel.getByText(/Automatic repair is exhausted/).first().isVisible());
  const implementationCount=()=>readFileSync(resolve(root,'.synthetic-calls.jsonl'),'utf8').trim().split('\n').map(JSON.parse).filter(r=>r.operation==='implement').length;
  const implemented=implementationCount();
  renameSync(resolve(root,'.synthetic-review-failure'),resolve(root,'.synthetic-review-failure-retained'));
  writeFileSync(resolve(root,'app.py'),'def answer():\n    return 2 # externally implemented after exhaustion\n');
  await assess();await panel.getByRole('button',{name:'Select external recipe',exact:true}).click();
  await panel.getByLabel('External author identity').fill('synthetic-external-author');await panel.getByLabel('Actual author provider').selectOption('human');
  result=await execute();assert.equal(result.view.status,'pending_manual_acceptance');assert.equal(implementationCount(),implemented);assert.equal(calls()-beforeExhaustion,9);
  view=await assess();
  await page.setViewportSize({width:390,height:844});
  await panel.getByRole('button',{name:'Select verify',exact:true}).scrollIntoViewIfNeeded();
  await panel.screenshot({path:resolve(artifacts,'operations-mobile.png')});
  assert(await panel.evaluate(e=>e.scrollWidth<=e.clientWidth+1),'Operation panel overflows mobile viewport');
  assert.deepEqual(errors,[]);
  const report={synthetic:true,browser:browser.version(),revision:execFileSync('git',['-C',repo,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),provider_calls:calls(),requests:readFileSync(resolve(root,'.synthetic-calls.jsonl'),'utf8').trim().split('\n').map(JSON.parse),usage:view.usage,provider_tokens:null,billed_cost:null,provider_cache_usage:null,checks:['evidence-bound clarification with no dispatch','reload-retained answer','per-case observation and evidence','UI/CLI admission parity','factory recipe','explicit bounded supervisor without redispatch','manual acceptance required','duplicate resume without dispatch','explicit acceptance','source drift','external adoption without implementation','failed verification remains failed','blocked review','reload persistence','three failed reviews exhaust bounded repair','external adoption after exhaustion without Implement','desktop/mobile rendering without script errors'],live_certification:false};
  writeFileSync(resolve(artifacts,'report.json'),JSON.stringify(report,null,2)+'\n');
  console.log(JSON.stringify(report));
} catch(error) {
  await page.screenshot({path:resolve(artifacts,'failure.png'),fullPage:true});
  console.error(await panel.innerText());
  throw error;
} finally {await browser.close();}
