#!/usr/bin/env bash
# nightshift-spec-digest.sh — produce a read-only SPEC-DIGEST.md for review agents.
#
# Reads docs/<task-key>/SPEC.md and writes docs/<task-key>/SPEC-DIGEST.md containing
# ONLY the Acceptance Criteria block and any Guardrails section. The full Solution /
# TRD body and Sources sections are excluded so the review lenses (nightshift-review) and
# any reviewer agents are not (a) paying tokens for implementation rationale, nor
# (b) anchored by it — they judge the diff against the contract, not the author's
# reasoning.
#
# Usage: nightshift-spec-digest.sh <task-key>
#
# The spec path is derived from the task-key internally; it is never taken as an
# argument (path-traversal guard).
#
# Output contract:
#   SPEC_DIGEST_WRITTEN: docs/<task-key>/SPEC-DIGEST.md   (success)
#   SPEC_DIGEST_SKIPPED: SPEC.md not found                (source missing, exit 0)
#   SPEC_DIGEST_SKIPPED: no task-key passed               (exit 0)
set -euo pipefail

PROJECT="$(python3 "$(dirname "${BASH_SOURCE[0]}")/nightshift-project-context.py" --root-only)" || exit $?
TASK="${1:-}"
[ -z "$TASK" ] && { echo "SPEC_DIGEST_SKIPPED: no task-key passed"; exit 0; }

SPEC_PATH="${PROJECT}/docs/${TASK}/SPEC.md"
DIGEST_PATH="${PROJECT}/docs/${TASK}/SPEC-DIGEST.md"

if [ ! -f "$SPEC_PATH" ]; then
  echo "SPEC_DIGEST_SKIPPED: SPEC.md not found"
  exit 0
fi

# Single-pass awk: keep a level-2 section iff its heading text is a target.
# Targets: "Acceptance Criteria" / "ACs" / anything ending in "Guardrails".
# Fenced code blocks are tracked so example headings inside ``` blocks don't flip
# the keep flag (prevents Solution-block examples leaking into the digest).
EXTRACTED=$(awk '
  function is_h2(line) { return (line ~ /^## /) }
  function norm(line,  s) {
    s = tolower(line)
    sub(/^##[[:space:]]+/, "", s)
    sub(/^[0-9]+\.[[:space:]]*/, "", s)   # strip "2. " numbering
    gsub(/[[:space:]]+$/, "", s)
    return s
  }
  function is_target(line,  t) {
    t = norm(line)
    if (t == "acceptance criteria") return 1
    if (t == "acs")                 return 1
    if (t ~ /guardrails$/)          return 1
    return 0
  }
  /^(```|~~~)/ { fence = !fence }
  {
    if (!fence && is_h2($0)) {
      keep = is_target($0)
    }
    if (keep) print
  }
' "$SPEC_PATH")

{
  echo "# SPEC-DIGEST: ${TASK}"
  echo "<!-- Generated by nightshift-spec-digest.sh. Do not edit. Source of truth: docs/${TASK}/SPEC.md -->"
  echo ""
  if [ -n "$EXTRACTED" ]; then
    printf '%s\n' "$EXTRACTED"
  else
    echo "<!-- No Acceptance Criteria or Guardrails sections found in SPEC.md -->"
  fi
} > "$DIGEST_PATH"

if [ -z "$EXTRACTED" ]; then
  echo "SPEC_DIGEST_WARNING: no AC or Guardrails sections found; wrote header-only digest"
fi

echo "SPEC_DIGEST_WRITTEN: docs/${TASK}/SPEC-DIGEST.md"
